# client-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients
spec:
  replicas: 10
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: curlimages/curl
        command: ["sh", "-c", "while true; do curl -s http://product-api-service/products; sleep 1; done"]