# client-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: client-load
spec:
  template:
    spec:
      containers:
      - name: load-tester
        image: curlimages/curl
        command: ["sh", "-c", "for i in $(seq 1 100); do curl -s http://product-api-service/products; done"]
      restartPolicy: Never
