apiVersion: v1
kind: Service
metadata:
  name: blockbuster-service
spec:
  type: NodePort
  selector:
    app: blockbuster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # o el puerto interno que tu app use
      nodePort: 30080   # <- este es el que va a hostPort: 8000
