apiVersion: apps/v1
kind: Deployment
metadata:
  name: festival-client
spec:
  replicas: 3  # Empezar con pocos para pruebas
  selector:
    matchLabels:
      app: festival-client
  template:
    metadata:
      labels:
        app: festival-client
    spec:
      containers:
      - name: client
        image: alpine
        command: ["sh", "-c"]
        args:
          - |
            apk add --no-cache curl;
            while true; do
              echo "=== $(date) ===";
              echo "Pod: $(hostname)";
              echo "Response:";
              curl -s -w "Status: %{http_code}\nTime: %{time_total}s\n" \
                http://festival-service.default.svc.cluster.local;
              echo "---------------";
              sleep $((RANDOM % 6 + 3));
            done