apiVersion: apps/v1
kind: Deployment
metadata:
  name: festival-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: festival
  template:
    metadata:
      labels:
        app: festival
    spec:
      containers:
      - name: festival-app
        image: festival-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: festival-service
spec:
  selector:
    app: festival
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer