apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: festival-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: festival-app  # ¡Apunta a tu Deployment!
  minReplicas: 1        # Mínimo de pods
  maxReplicas: 10       # Máximo de pods bajo carga
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Escala si el uso promedio de CPU supera el 50%